### ISSUE TITLE
Using DATA is nice, but makes it hard to update

### ISSUE THREAD

**Issue by hanshasselberg** [torsten/cheat#1]
Since everybody has its own data I image it to be hard to upgrade to future versions b/c you have to tamper with `cheat.rb`.
I am suggesting to extract the data into a small database - perhaps `~/.cheat_db`. What do you think?

**Comment by torsten** [comment]
Hmm, in general I would like to keep it really simple.

For now I went with a branch for my own cheats: https://github.com/torsten/cheat/tree/torsten/cheats

The plan would then be to merge master into my own branch once logic changes.

Let me think about the extra file a bit. :)
