### ISSUE TITLE
I want to execute a command right away

### ISSUE THREAD

**Issue by hanshasselberg** [torsten/cheat#3]
Like that:

```
$ cheat ntp
Time

  sudo ntpdate -u ntp.ubuntu.com
$ `cheat` # doesn't work b/c its not only the command
```

**Comment by torsten** [comment]
Good idea.  Since I am not using cheat in that way yet it did not really occur to me. :>

I can think of two ways:

**1. Whenever only one command matches ask to execute it like this:**

``` bash
$ cheat ntp  
Time

  sudo ntpdate -u ntp.ubuntu.com

Execute now? [y/n]: _
```

**2. Adding a `--run` flag**

This might be more explicit and would like this

``` bash
$ cheat -run ntp
[ntpdate output here]
```

What do you think?

**Comment by hanshasselberg** [comment]
I thought of something else :>. What about writing the title to `stderr` and the command to `stdout`? you could then use the back ticks I think :)

**Comment by torsten** [comment]
That won't work with the search-term highlighting because `cheat` inserts escape characters which the shell trys to execute.

``` bash
$ `cheat foo`
zsh: command not found: ^[[1m#
```

**Comment by torsten** [comment]
I think I found a way to make backticks work:

`$SHLVL` is increased every time a sub shell starts, but when running ruby in backticks it is `0`.

Does this script work for you?  This is the output I get:

``` bash
$ ./backtick.rb
Title

  ls
$ `./backtick.rb`
README.md   backtick.rb cheat.rb
```

Here is `backtick.rb`:

``` ruby
#!/usr/bin/env ruby

level = ENV["SHLVL"].to_i

if level == 0
  puts "ls"
else
  puts "Title\n\n  ls\n"
end
```

**Comment by hanshasselberg** [comment]
works! :rocket:

**Comment by torsten** [comment]
Does this solve the issue for you? :)

**Comment by hanshasselberg** [comment]
Yes I think so! Thanks!!
