### ISSUE TITLE
Release as Ruby Gem

### ISSUE THREAD

**Issue by parkr** [torsten/cheat#4]
Releasing this bad boy as a Ruby Gem would be pretty freaking cool, and allow for easier versioning, etc. Installation would be even easier with `gem install cheat.rb`.

Would also nicely decouple for a solution to #1.

**Comment by torsten** [comment]
OK, you and @i0rek have convinced me :)

What do you think about using `CHEAT_FILE` from the env and falling back to `~/.cheat` as the file that will be read by default?

**Comment by hanshasselberg** [comment]
sounds good!

**Comment by parkr** [comment]
> What do you think about using CHEAT_FILE from the env and falling back to ~/.cheat as the file that will be read by default?

:+1:
